### PR TITLE
Update Gopkg.lock to get latest flux dependencies.

### LINKED ISSUE #1331: fluxctl port forward is broken on GKE
Once this PR gets merged https://github.com/justinbarrick/go-k8s-portforward/pull/2/files the portforward package has to be updated in Flux.

### PR DESCRIPTION
**Pull request by justinbarrick**
Fixes #1331.

### CODE REVIEW

**Comment by rade** [comment]
Why is the diff so huge? In particular, why do we suddenly end up with `digest` and `pruneopts` on every entry?

**Comment by justinbarrick** [comment]
I’m not certain, I just ran `dep ensure` on the latest master. Is there a preferred way to do it?

**Comment by rade** [comment]
> Is there a preferred way to do it?

[Yes](https://github.com/weaveworks/flux/blob/master/site/building.md#dependency-management).

**Comment by hiddeco** [comment]
> [Yes.](https://github.com/weaveworks/flux/blob/master/site/building.md#dependency-management)

Quite funny as `dep ensure` tells you running `dep prune` is obsolete [[1]](https://github.com/golang/dep/issues/1820#issuecomment-383343883).

**Comment by justinbarrick** [comment]
There is no apparent way to update only the go-k8s-portforward pin in Gopkg.lock.

I get the same result whether I do:

```
dep ensure
```

Or:

```
dep ensure && dep prune
```

Or:

```
dep ensure -update github.com/justinbarrick/go-k8s-portforward
```

And the following fails because it was already there:

```
dep ensure -add github.com/justinbarrick/go-k8s-portforward
```

As far as I can tell, even if it was possible to force just an update of go-k8s-portforward in the Gopkg.lock, users that ran `dep ensure` (CI, the docs, etc) would get the same result I'm getting now.

@stefanprodan seemed worried about getting this out, so maybe he can comment.

**Comment by rade** [comment]
I wonder whether the cause of the large diff is a dep version change. When I run `dep ensure && dep prune` on master I get the following diff:
```diff
diff --git a/Gopkg.lock b/Gopkg.lock
index e21c866..544f79d 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -1,6 +1,25 @@
 # This file is autogenerated, do not edit; changes may be undone by the next 'dep ensure'.
 
 
+[[projects]]
+  name = "cloud.google.com/go"
+  packages = ["compute/metadata"]
+  revision = "c728a003b238b26cef9ab6753a5dc424b331c3ad"
+  version = "v0.27.0"
+
+[[projects]]
+  name = "github.com/Azure/go-autorest"
+  packages = [
+    "autorest",
+    "autorest/adal",
+    "autorest/azure",
+    "autorest/date",
+    "logger",
+    "version"
+  ]
+  revision = "a35eae345f69bbfbe3b8fa0b1d3fe98f8430b21a"
+  version = "v10.15.3"
+
 [[projects]]
   name = "github.com/BurntSushi/toml"
   packages = ["."]
@@ -31,6 +50,12 @@
   revision = "346938d642f2ec3594ed81d874461961cd0faa76"
   version = "v1.1.0"
 
+[[projects]]
+  name = "github.com/dgrijalva/jwt-go"
+  packages = ["."]
+  revision = "06ea1031745cb8b3dab3f6a236daf2b0aa468b7e"
+  version = "v3.2.0"
+
 [[projects]]
   branch = "master"
   name = "github.com/docker/distribution"
@@ -191,6 +216,20 @@
   revision = "ee43cbb60db7bd22502942cccbc39059117352ab"
   version = "v0.1.0"
 
+[[projects]]
+  branch = "master"
+  name = "github.com/gophercloud/gophercloud"
+  packages = [
+    ".",
+    "openstack",
+    "openstack/identity/v2/tenants",
+    "openstack/identity/v2/tokens",
+    "openstack/identity/v3/tokens",
+    "openstack/utils",
+    "pagination"
+  ]
+  revision = "d629ff82f917578016e3f92bf521cc52459c4290"
+
 [[projects]]
   name = "github.com/gorilla/context"
   packages = ["."]
@@ -253,8 +292,8 @@
 [[projects]]
   name = "github.com/justinbarrick/go-k8s-portforward"
   packages = ["."]
-  revision = "b691ffe85e96a3e4ce5de9d8a17f1f884190e6d0"
-  version = "v1.0.0"
+  revision = "d39d2092197c730c96523ab78491f481860eaa89"
+  version = "v1.0.1"
 
 [[projects]]
   branch = "master"
@@ -430,6 +469,7 @@
   name = "golang.org/x/net"
   packages = [
     "context",
+    "context/ctxhttp",
     "http2",
     "http2/hpack",
     "idna",
@@ -439,6 +479,18 @@
   ]
   revision = "cbe0f9307d0156177f9dd5dc85da1a31abc5f2fb"
 
+[[projects]]
+  branch = "master"
+  name = "golang.org/x/oauth2"
+  packages = [
+    ".",
+    "google",
+    "internal",
+    "jws",
+    "jwt"
+  ]
+  revision = "d2e6202438beef2727060aa7cabdd924d92ebfd9"
+
 [[projects]]
   branch = "master"
   name = "golang.org/x/sys"
@@ -475,6 +527,23 @@
   packages = ["rate"]
   revision = "6dc17368e09b0e8634d71cac8168d853e869a0c7"
 
+[[projects]]
+  name = "google.golang.org/appengine"
+  packages = [
+    ".",
+    "internal",
+    "internal/app_identity",
+    "internal/base",
+    "internal/datastore",
+    "internal/log",
+    "internal/modules",
+    "internal/remote_api",
+    "internal/urlfetch",
+    "urlfetch"
+  ]
+  revision = "b1f26356af11148e710935ed1ac8a7f5702c7612"
+  version = "v1.1.0"
+
 [[projects]]
   branch = "master"
   name = "google.golang.org/genproto"
@@ -680,10 +749,16 @@
     "pkg/apis/clientauthentication/v1alpha1",
     "pkg/apis/clientauthentication/v1beta1",
     "pkg/version",
+    "plugin/pkg/client/auth",
+    "plugin/pkg/client/auth/azure",
     "plugin/pkg/client/auth/exec",
+    "plugin/pkg/client/auth/gcp",
+    "plugin/pkg/client/auth/oidc",
+    "plugin/pkg/client/auth/openstack",
     "rest",
     "rest/watch",
     "testing",
+    "third_party/forked/golang/template",
     "tools/auth",
     "tools/cache",
     "tools/clientcmd",
@@ -703,6 +778,7 @@
     "util/flowcontrol",
     "util/homedir",
     "util/integer",
+    "util/jsonpath",
     "util/retry",
     "util/workqueue"
   ]
@@ -762,6 +838,6 @@
 [solve-meta]
   analyzer-name = "dep"
   analyzer-version = 1
-  inputs-digest = "2c24153e0bc861ad36def5316832ca62468561105ca3996b996e7cb7131cca4b"
+  inputs-digest = "c3d3434cc6f68a60307306dd95b3f4c219c75cd611118ad54506fbc48e351ecf"
   solver-name = "gps-cdcl"
   solver-version = 1
```
That looks much more reasonable. My dep version is
```
$ dep version
dep:
 version     : v0.4.1
 build date  : 2018-01-24
 git hash    : 37d9ea0a
 go version  : go1.9.1
 go compiler : gc
 platform    : linux/amd64
```

**Comment by justinbarrick** [comment]
I'm using the latest from git:

```
go get -u github.com/golang/dep/cmd/dep
```

I'll try to find yours and see what happens.

**Comment by justinbarrick** [comment]
Yeah, I get the same result as you @rade when I use your version of dep. How do you want to proceed?

**Comment by justinbarrick** [comment]
In CI, you use latest dep, so we should probably leave this as-is?

https://github.com/weaveworks/flux/blob/master/.circleci/config.yml#L12-L13

**Comment by rade** [comment]
Using the latest master version of `dep` strikes me as a bad idea. We could switch to the latest released version, but not in the same PR as making a substantive change. (And yes, we should change the circleci config to use a released version, too).

So I suggest we stick to 0.4.1 for this PR.

**Comment by squaremo** [comment]
Thanks @justinbarrick :bento:

**Pull request merged**
