### PR TITLE
Bump kubeyaml to version 0.5.2

### PR DESCRIPTION
**Pull request by 2opremio**
Needed for https://github.com/weaveworks/flux/issues/1925

### CODE REVIEW

**Comment by hiddeco** [comment]
I think https://github.com/weaveworks/flux/blob/master/bin/kubeyaml also needs an update.

**Comment by 2opremio** [comment]
Yep, I will rebuild once that's done

**Comment by 2opremio** [comment]
Oh, true

**Comment by squaremo** [comment]
> I will rebuild once that's done

The script in bin/kubeyaml needs the version updated as well

**Pull request merged**
