### PR TITLE
Try a 'fluxctl status' command

### LINKED ISSUE #244: Status monitoring
It would be useful to have a way to confirm flux is running properly. I would propose:

* A Status command, contacting the backend and showing everything is OK.
* Prometheus metrics (and grafana graphs).

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #244

@squaremo, wdyt?

I'm not really convinced on the distinction between this and `IsConnected`, but this format gives us more room for the status of various bits.. It's also a bit unclear on the distinction between this and `GetConfig`. Suggestions?

### CODE REVIEW

**Comment by squaremo** [comment]
Could it be implemented just by calling `GetConfig` and `IsConnected` from the client? I guess that would mean it's more difficult to add information in.

**Comment by paulbellamy** [comment]
Hmm, I added it as a separate method, so we could try other things to verify it was set up correctly, like cloning the repo. I've added that into this PR.

So if you have misconfigured your git public key you'll get:
```
$ fluxctl status
fluxd:
  connected: true
git:
  configured: true
  error: 'git clone: exit status 128'
```

**Comment by paulbellamy** [comment]
Rebased

**Comment by paulbellamy** [comment]
As raised in: https://github.com/weaveworks/flux/issues/337 it would be good to output the *reason* for the git failure.

Multiline strings get rendered well by the go yaml library we're using, e.g.
```Go
yaml.Marshal(map[string]string{
	"field1": "1234",
	"field2": "abcd\nefgh\nijkl",
})
```
renders...
```yaml
field1: "1234"
field2: |-
  abcd
  efgh
  ijkl
```
So we could put out the git stderr into the status response, and it should render well.

**Comment by paulbellamy** [comment]
Have added git clone stderr into the `status` reponse:
```
$ fluxctl status
fluxd:
  connected: true
  version: HEAD-00fa07e-WIP
git:
  configured: true
  error: |
    Cloning into '/tmp/flux-gitclone819220243/repo'...
    Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```

**Pull request merged**
