### PR TITLE
add snapcraft.yaml for Linux packages of fluxctl

### PR DESCRIPTION
**Pull request by dholbach**
This creates a snap of `fluxctl`, prerequisite is:

```console
sudo snap install snapcraft --classic
sudo snap install multipass --beta --classic
snapcraft
```

Next step would be 

- [x] register on Snap store
- [x] push initial snap of 'edge' release (current HEAD)
- [x] ask for ~~classic~~ `personal-files` permissions (https://forum.snapcraft.io/c/store-requests)
- [x] get package ~~and classic permissions~~ approved
- [x] ~~hook this up with the build infrastructure~~ → moving this to a new issue/OR

### CODE REVIEW

**Comment by dholbach** [comment]
https://forum.snapcraft.io/t/fluxctl-snap-want-to-be-classic/11073/2 is the current stand of things.

**Comment by squaremo** [comment]
What're the minikube files mentioned in the YAML @dholbach ?

**Comment by dholbach** [comment]
They're not really required. Removing.

**Comment by dholbach** [comment]
@squaremo Apparently, they're needed after all:

```
[daniel@reef flux ]$ fluxctl identity
Error: Could not load kubernetes configuration file: invalid configuration: [unable to read client-cert /home/daniel/.minikube/client.crt for minikube due to open /home/daniel/.minikube/client.crt: permission denied, unable to read client-key /home/daniel/.minikube/client.key for minikube due to open /home/daniel/.minikube/client.key: permission denied, unable to read certificate-authority /home/daniel/.minikube/ca.crt for minikube due to open /home/daniel/.minikube/ca.crt: permission denied]
Run 'fluxctl identity --help' for usage.
[daniel@reef flux ]$ 
```

**Comment by squaremo** [comment]
> they're needed after all

What about people that aren't using minikube? What exactly is the purpose of that section of the YAML?

**Comment by dholbach** [comment]
This part of the YAML allows `fluxctl` to read these files.

**Comment by dholbach** [comment]
The package was approved in the Snap store. I pushed it to the `edge` channel.

Running `snap install --edge fluxctl` will download and install it. Testing welcome.

Next step would be to hook it up with our build infrastructure.

**Comment by 2opremio** [comment]
Great job @dholbach !!!

**Comment by dholbach** [comment]
Maybe let's merge this as is for now and then solve whatever's required for publishing master builds to `edge` and tagged commits to `stable`.

**Comment by dholbach** [comment]
I pushed a `stable` (1.12.3) `fluxctl` to the store now too. Time to hook things up with CI.

**Pull request merged**
