### PR TITLE
Migrate dependency management to Go modules

### PR DESCRIPTION
**Pull request by 2opremio**
Also:
* Make `$GOBIN` work
* Cache go modules

`$GOPATH` is not required anymore. @hiddeco @squaremo @stefanprodan make sure to move your Flux outside of `$GOPATH` once this is merged (the alternative is to prepend every single `go` invocation by `GO111MODULE=on` which I ended up discarding)

### CODE REVIEW

**Comment by 2opremio** [comment]
Close, but no cigar :( https://github.com/kubernetes/kubernetes/issues/67566

**Comment by squaremo** [comment]
> Close, but no cigar :( [kubernetes/kubernetes#67566](https://github.com/kubernetes/kubernetes/issues/67566)

lolk8s :-(

**Comment by 2opremio** [comment]
Huhm, there seems to be a solution https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by 2opremio** [comment]
The build time goes down to 8.5 minutes since, unlike `dep`, `go mod` caches dependencies.

**Comment by 2opremio** [comment]
Great, you can actually stop defining GOPATH altogether

**Pull request merged**
