### PR TITLE
docs: explain GitOps concept and flux's role

### PR DESCRIPTION
**Pull request by dholbach**
Explain the concept of GitOps in the main README.md and detail flux's
role in this. Add a diagram to illustrate. Spell out the benefits of
using flux more clearly.

Add links to discussion of specific features.

Reflow documentation links.

Point to `#flux` Slack channel instead of `#general`.

### CODE REVIEW

**Comment by dholbach** [comment]
Thanks @squaremo for the review. I addressed your comments and updated the heading in `introduction.md` as well.

**Comment by dholbach** [comment]
@squaremo Can you comment on @stefanprodan's suggestion? I like it and happy to make the change in this PR.

**Comment by stefanprodan** [comment]
The change has to be done in Github UI since the description is not part of the readme.

**Comment by dholbach** [comment]
Nevermind then. You go on without me. :-)

**Comment by squaremo** [comment]
> I would change the repo description from A tool for deploying container images to Kubernetes services to The GitOps Kubernetes Operator

Good suggestion! I also added `gitops` to the keywords.

**Pull request merged**
