### PR TITLE
Prevent auto-upgrade before lock in annotations tutorial

### LINKED ISSUE #1983: Workload autoupgraded before locking in annotations tutorial
Currently if you follow along with the https://github.com/weaveworks/flux/blob/master/site/annotations-tutorial.md example between the time you release 1.4.1 and you lock the deployment gets auto-upgraded to latest 1.4.x tag and therefore when you lock it locks on latest version. 

I would suggest therefore allowing the "lock" to be passed as a flag to release.

Something similar to:
```
fluxctl release --workload demo:deployment/podinfo -i stefanprodan/podinfo:1.4.1 --lock --lock-msg="1.4.2 does not work for us"
```

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #1983

### CODE REVIEW

**Comment by squaremo** [comment]
Rebasing on master should fix the CI failure

**Comment by 2opremio** [comment]
@squaremo done!

**Comment by squaremo** [comment]
You could just reverse the order of the lock / rollback release such that it's locked first (then use `--force` with the rollback release, to make it ignore the lock for that command).

**Comment by dholbach** [comment]
Will https://github.com/weaveworks/flux/commit/0ca2796c9c872e3f081fbeb137a99c07a4c9ae7c#diff-15622267c2ec3db7451cdecfe25640b9 need to be applied as well here?

**Comment by dholbach** [comment]
Apart from that :+1:

**Comment by 2opremio** [comment]
> You could just reverse the order of the lock / rollback release such that it's locked first (then use --force with the rollback release, to make it ignore the lock for that command).

Good idea! I wasn't aware of the `--force` flag

**Comment by 2opremio** [comment]
> Will [0ca2796#diff-15622267c2ec3db7451cdecfe25640b9](https://github.com/weaveworks/flux/commit/0ca2796c9c872e3f081fbeb137a99c07a4c9ae7c#diff-15622267c2ec3db7451cdecfe25640b9) need to be applied as well here?

I think so, but I will do it in a separate PR.

**Comment by 2opremio** [comment]
@squaremo I redid it using your suggestion.

**Pull request merged**
