### PR TITLE
Give container images labels

### PR DESCRIPTION
**Pull request by squaremo**
Appropriate labelling per http://label-schema.org/rc1/. Most of it is static, other than the revision, which is supplied when building.

### CODE REVIEW

**Comment by squaremo** [comment]
Curses, this needs a far newer version of Docker than Circle 1.0 provides. Would need to upgrade to Circle 2.0 most likely.

**Comment by squaremo** [comment]
Closing to take off the radar, as I don't yet want to go through the pain of updating our CI.

**Comment by leth** [comment]
@awh solved the pain, is this worth reopening?

**Comment by squaremo** [comment]
> @awh solved the pain, is this worth reopening?

Yas! Might need some rebass, mind you.

**Pull request merged**
