### PR TITLE
Generate and write git deploy key from the cli.

### PR DESCRIPTION
**Pull request by philwinder**
- Added key generator
- Added new command and api to generate key

Note that this only generates and writes the key. It does not connect to github to automatically update the key there, yet.

### CODE REVIEW

**Comment by squaremo** [comment]
I'd prefer it if there were one way of accomplishing this, rather than both an option and a subcommand. 

Personally I'd go for the option, since it means you can configure an instance in one step (fill out the other config, then call `fluxctl set-config -f conf --generate-key`).

On expanding the API, until we know how integration with the web UI works, I don't think it's worth adding it (or holding this PR up). For example, if it turns out that the best thing is to select the specific repo and path at the same time in the UI, then the API as given will be immediately obsolete. So I would just handle the `--generate-keys` option in the set-config handler for now.

**Comment by philwinder** [comment]
@squaremo See fixes above. Commands now look like the example below:

```
$ fluxctl get-config
git:
  URL: ""
  path: ""
  branch: ""
  key: ""
slack:
  hookURL: ""
  username: ""
registry:
  auths: {}

$ set-config -k

$ get-config
git:
  URL: ""
  path: ""
  branch: ""
  key: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcqOZRVDi2Gv1hivfb4OBJHqLo4zQCdRaJLko2yaFvN17/uCddXfXiAD1TArq2Bz0SiVKVWjlsjneKFdVhdYqZhMDXchfMrNoKUuSuW54QOLI+L5IVAZwF80SUxRXHlk1kTh0dN9SgQC854KVUOioGZbBgDE3gVtfEk9NUlRQrXDtp2ZbqcgHJD70Ndq+hKgfqh+00XkEncfewZM4LAHyUr8lvIajAZqN2i3d/w2Bvb/nF0H1WG0oWvH5h5sVKoJCDYRJWrSg3L35vvF5MeaK2DCzagbYydvk/I9GikvsQj0Sk10Br92akO608ZUt7xqH4usElLjG2FYLtFiWHGJGA+teIpnNlSBGO4blHgMxjS+c3bmozFCh0IDcAM+85RHBPJ3sLby3Ze+h9fWcIw2cgIve7XimGbfXuBHlwKoA5nY7469yUNa6m7Yhao/ZuJPZYMHQJKy7zqvU3oUqzVot8v15fG9yJsRm1AWQwd2Yufbk/d917RakpWAPolx1C/eiE0n+s02XjSRvJGg6/PK8IswtB/a8hvUdnfdymCr3VVuYik4wQPj0WHsGM78wFSMG2aaU5cR96WQnfB/tBdHxMAfvOwTwkr35srEqem04marnnU4ruEORc7TezXGA5aGobeBKpbGaVbVeoUPxSNs57TXXK3LPpUD5MTZP8mHoIPQ==
slack:
  hookURL: ""
  username: ""
registry:
  auths: {}

$ set-config --file=flux.yml --generate-deploy-key

$ get-config
git:
  URL: git@github.com:philwinder/flux-example
  path: ""
  branch: master
  key: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpLFEqGkBcsFRyx2xj9YEsYzxeMXQf4Jzm+z2403HE2DJ1i2+wGuad2oYqa1eylw0/3nh73IczcV5vzkmc1ZIdRqpK73MoqzCJk9cR5qYeGUhPXn0HxErRt3TOs0dH/50L8lAtIJLYD0tXaySnFDpYq5iz7HPpIGU62TZbLwz+vye9WCvUi+eJFI7S0sZs6uYab7iQN8OLGRQXNkDqQRlI0yV7twRKgo2obyPkaFpDDZJpZF/jY+9QgAQstDHDAJ7oA6s64z7plujfZNHewDtcaDT0y/+XoFJs4WTXLQgmY2krGP4UdcPowsWDV1VmapsWfIa90uCAqC3D7Qh/CfqhxJb7BoY1SCyjnZwic7a3RYTl10UlGQx2oMFwqcYpPcJz6UpvgQy6PHTVlS3Rzu1isPOq4JeiZK7vSkA9c0MoRud+FaaWVfIR8/jyQDM+ZP5L0vVfJpdz9EHx6lEkJ6XfCbmzBdBgJatc5GzQ9H6eMKzNc9GstbIMG/FGOXeHGBrZxgoKELbAoOiRHaFQnW2mnaeO5+LXA/WdiztjVnXEtYp1P6f0C9nyQNKA+nBSMAkQtgEjsZY01sqYj7DqZm98J6FmoFazgjc3M5ns+inbqxBQQF509qOirxb1yz4b0ddExihRkIQuJHEUjF6ag5NZtBXrQKKzkFy2eLYFVTSMFQ==
slack:
  hookURL: ""
  username: ""
registry:
  auths: {}

$ set-config
Usage:
  fluxctl set-config [flags]

Examples:
  fluxctl set-config --file=./dev/flux-conf.yaml --generate-deploy-key

Flags:
  -f, --file string           A file to upload as configuration; this will overwrite all values.
  -k, --generate-deploy-key   Generate and replace Git deploy key
  -h, --help                  help for set-config

Global Flags:
  -t, --token string   Weave Cloud service token; you can also set the environment variable FLUX_SERVICE_TOKEN
  -u, --url string     base URL of the flux service; you can also set the environment variable FLUX_URL (default "https://cloud.weave.works/api/flux")
```

**Comment by squaremo** [comment]
> I am a little uneasy about introducing such a specific API for generating keys -- it seems likely to change, so it's more compatibility to maintain. On the other hand, it needs a change to the API somewhere. (Could be another argument to SetConfig?)

*New endpoint*

 - Can have its own return value (probably the public key), which might be convenient for the web UI

*Option to SetConfig*

 - Doesn't need as much boilerplate as a new endpoint

**Comment by squaremo** [comment]
Reminder: this can be merged. I am dithering about the pros and cons of how to represent it in the API, but you don't have to indulge it @philwinder .

**Pull request merged**
