### PR TITLE
Bump fluxd and helm-op versions, and Helm chart version

### PR DESCRIPTION
**Pull request by stefanprodan**
- includes Flux v1.7.0 and Flux Helm Operator v0.2.1

### CODE REVIEW

**Comment by squaremo** [comment]
I'm confused about when we need to update the chart with new versions. What's the policy?

**Comment by stefanprodan** [comment]
We need to update the chart every time we do a Flux/helm-op release or when we modify something in the yamls.

**Comment by squaremo** [comment]
> We need to bump the chart version every time we do a Flux/helm-op release

Why? The version of both those things are parameters to the chart.

**Comment by stefanprodan** [comment]
but that means that all our tutorials should include hardcoded versions. Also when someone will use the Helm chart with the default install command they will get older versions.

**Comment by stefanprodan** [comment]
Here is an example from the official Helm repo https://github.com/helm/charts/commits/master/stable/drupal/Chart.yaml

**Comment by squaremo** [comment]
Why have the versions as parameters then?

**Pull request merged**
